### ISSUE TITLE
Certain hues not displaying

### ISSUE THREAD

**Issue by jlmosesman** [jonsamp/codecademy-syntax#4]
I had this theme installed and running beautifully at one point, and even when I started working in Elixir the highlighting was exactly what I expected.

After a machine wipe and a reinstall, some of the hues in Ruby are not displaying.

<img width="322" alt="screen shot 2018-11-07 at 2 35 23 pm" src="https://user-images.githubusercontent.com/31223596/48159385-a53ed700-e29a-11e8-922a-ee8e36f3a226.png">

For example from what I'm used to and what Codecademy actually shows, the `me`  variable should be orange, the `Person` red and `.new` cyan.

HTML and CSS syntax coloring work as expected.

Do you know of a possible way to fix this?

**Comment by jonsamp** [comment]
Hey @jlmosesman,

Finally got to this. I got Ruby syntax highlighting into a better spot. It is not _exactly_ our styles on the website, but that's because Atom's selectors are less specific in some cases and I cannot highlight certain entities how I would like.

I hope this improves your editor experience!

<img width="1189" alt="screen shot 2018-11-25 at 8 52 20 pm" src="https://user-images.githubusercontent.com/6455018/48988681-ba1dc600-f0f4-11e8-952d-0d4c37b903ab.png">
